version: "3.3"
services:
  web:
    container_name: web
    build: ./DnaVastgoed/
    ports:
      - "5000:80"
      - "5001:443"
    env_file:
      - .env
    volumes:
      - ./Database:/Database
      - ~/.aspnet/https:/https:ro
    restart: on-failure
